# Generated by Django 6.1.1 on 2026-09-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.PositiveIntegerField()),
                ('street_side', models.CharField(default='LEFT', max_length=5)),
                ('house_facade', models.CharField(default='🏠 Casa contemporánea', max_length=100)),
                ('resident_name', models.CharField(default='Residente', max_length=100)),
                ('occupant_role', models.CharField(default='Dueño(a) de casa', max_length=100)),
                ('archetype', models.CharField(choices=[('BUSY', 'El Ocupado / Con Prisa'), ('SKEPTICAL', 'El Desconfiado / Escéptico'), ('POLITE_EVASIVE', 'El Amable Evasivo ("Déjeme un folleto")'), ('HOSTILE', 'El Hostil / Malhumorado'), ('IDEAL_LEAD', 'El Prospecto Ideal / Calificado'), ('NOT_HOME', 'Nadie en Casa')], default='SKEPTICAL', max_length=30)),
                ('status', models.CharField(choices=[('UNVISITED', 'Sin visitar'), ('NOT_HOME', 'Nadie atiende'), ('IN_PROGRESS', 'En conversación'), ('REJECTED', 'Rechazado'), ('APPOINTMENT', 'Cita agendada'), ('SALE_CLOSED', 'Venta cerrada')], default='UNVISITED', max_length=20)),
                ('interest', models.IntegerField(default=30)),
                ('patience', models.IntegerField(default=50)),
                ('current_node', models.CharField(default='start', max_length=50)),
                ('dialogue_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('target_type', models.CharField(choices=[('RESIDENTIAL', 'Zona Residencial'), ('COMMERCIAL', 'Corredor Comercial')], default='RESIDENTIAL', max_length=20)),
                ('description', models.TextField()),
                ('door_count', models.PositiveIntegerField(default=10)),
                ('open_rate', models.PositiveIntegerField(default=75, help_text='Porcentaje de probabilidad de que alguien abra la puerta (0-100)')),
                ('economic_level', models.CharField(default='Medio', max_length=50)),
                ('difficulty', models.CharField(default='Normal', max_length=20)),
                ('badge_color', models.CharField(default='emerald', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residencial (Hogares)'), ('COMMERCIAL', 'Comercial (Negocios / Pymes)')], default='RESIDENTIAL', max_length=20)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('commission_per_sale', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('commission_per_appointment', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('difficulty_multiplier', models.FloatField(default=1.0)),
                ('icon_emoji', models.CharField(default='📡', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DoorInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField(default=1)),
                ('prospect_statement', models.TextField()),
                ('player_choice_text', models.TextField()),
                ('coach_critique', models.TextField()),
                ('tactic_type', models.CharField(default='General', max_length=50)),
                ('interest_change', models.IntegerField(default=0)),
                ('patience_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='simulator.door')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField(default=100)),
                ('morale', models.IntegerField(default=100)),
                ('current_time_str', models.CharField(default='09:00 AM', max_length=20)),
                ('doors_knocked', models.PositiveIntegerField(default=0)),
                ('doors_opened', models.PositiveIntegerField(default=0)),
                ('pitches_started', models.PositiveIntegerField(default=0)),
                ('appointments_booked', models.PositiveIntegerField(default=0)),
                ('sales_closed', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('coach_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.neighborhood')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_days', to='core.prospectorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='simulation_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='simulator.simulationday'),
        ),
    ]
