# Generated by Django 6.1.1 on 2026-09-25 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vendedor Novato', max_length=100)),
                ('avatar_emoji', models.CharField(default='🚶\u200d♂️', max_length=10)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('cash_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('empathy', models.PositiveIntegerField(default=3, help_text='Mejora la detección de necesidades y reduce la desconfianza')),
                ('persuasion', models.PositiveIntegerField(default=3, help_text='Aumenta el impacto positivo al rebatir objeciones')),
                ('resilience', models.PositiveIntegerField(default=4, help_text='Reduce el desgaste de moral y energía tras rechazos')),
                ('closing_skill', models.PositiveIntegerField(default=2, help_text='Aumenta la tasa de éxito al pedir la cita o la venta')),
                ('total_days_worked', models.PositiveIntegerField(default=0)),
                ('total_doors_knocked', models.PositiveIntegerField(default=0)),
                ('total_doors_opened', models.PositiveIntegerField(default=0)),
                ('total_objections_handled', models.PositiveIntegerField(default=0)),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_rejections', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospector_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
